In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

In [6]:
a=np.array([[10,20,30],[1,2,3]])
print(a)

[[10 20 30]
 [ 1  2  3]]


In [9]:
a.shape

(2, 3)

In [10]:
a.size

6

In [11]:
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[1,2,3],[7,8,9]])
print("Result:",a+b)

Result: [[11 22 33]
 [ 8 10 12]]


In [12]:
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[1,2,3],[7,8,9]])
print("Result1:",a+5)
print("Result2:",b-5)

Result1: [[15 25 35]
 [ 6  7  8]]
Result2: [[-4 -3 -2]
 [ 2  3  4]]


In [13]:
a=np.array([[10,20,30],[1,2,3]])
a.flatten()
print(a)

[[10 20 30]
 [ 1  2  3]]


In [16]:
a=np.array([[10,20,30],[1,2,3],[10,2,3]])
b=a.reshape(3,3)
print(b)

[[10 20 30]
 [ 1  2  3]
 [10  2  3]]


In [20]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [21]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [26]:
a=np.full((2,3),4)
print(a)

[[4 4 4]
 [4 4 4]]


In [27]:
a=np.array([[10,20,30],[1,2,3]])
r=a.ravel()
r[0]=90
print(r)

[90 20 30  1  2  3]


In [29]:
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[1,2,3],[7,8,9]])
print("Result:",np.concatenate((a,b),axis=0))

Result: [[10 20 30]
 [ 1  2  3]
 [ 1  2  3]
 [ 7  8  9]]


In [30]:
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[1,2,3],[7,8,9]])
print("Result:",np.sort((a,b),axis=0))

Result: [[[ 1  2  3]
  [ 1  2  3]]

 [[10 20 30]
  [ 7  8  9]]]


In [34]:
a=np.ones((2,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


In [35]:
a=np.array([[10,20,30],[1,2,3]])
a.ndim

2

In [41]:
a=np.array([[10,20,30],[1,2,3]])
print(a[0])

[10 20 30]


In [42]:
a=np.array([[10,20,30],[1,2,3]])
print(a[2:])

[]


In [44]:
a=np.array([[10,20,30,1,2,3]])
print(a[0:])

[[10 20 30  1  2  3]]


In [45]:
a=np.array([[10,20,30,1,2,3]])
print(a[::2])

[[10 20 30  1  2  3]]


In [47]:
a=np.array([[10,20,30],[1,2,3]])
print("Sum:",np.sum(a,axis=0))


Sum: [11 22 33]


In [50]:
a=np.array([[10,20,30],[1,2,3]])
print("Sum:",np.sum(a,axis=1))

Sum: [60  6]


In [52]:
a=np.array([[10,20,30],[1,2,3]])
print("Sum:",np.max(a,axis=1))
print("Sum:",np.min(a,axis=1))

Sum: [30  3]
Sum: [10  1]
